version: '2'
services:
  db:
    image: postgres:15
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2024
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - my-main-net

  odoo18:
    image: odoo:18
    user: root
    depends_on:
      - db
    ports:
      - "10018:8069"   # main Odoo
      - "20018:8072"   # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo18@2024
    volumes:
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh
      - ./enterprise-addons:/mnt/enterprise-addons  # Mount enterprise addons
      - ./custom-addons:/mnt/custom-addons          # Mount custom addons
      - ./etc:/etc/odoo  
      
    networks:
      - my-main-net
    restart: always
networks:
  my-main-net:
    external: true

command: odoo --addons-path=/mnt/enterprise-addons,/mnt/custom-addons,/usr/lib/python3/dist-packages/odoo/addons

